name: TRF_GBO_PhD
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - arrow=1.3.0
  - astroid=3.2.4
  - asttokens=2.0.5
  - async-timeout=4.0.3
  - asyncssh=2.17.0
  - atomicwrites=1.4.0
  - attrs=24.2.0
  - autopep8=2.0.4
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=24.8.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2025.2.25
  - certifi=2024.8.30
  - cffi=1.17.1
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.0.5
  - cookiecutter=2.6.0
  - cryptography=43.0.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - diff-match-patch=20200713
  - dill=0.3.8
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - executing=0.8.3
  - flake8=7.1.1
  - fonttools=4.51.0
  - freetype=2.13.3
  - frozenlist=1.4.0
  - gmpy2=2.1.2
  - icu=73.1
  - idna=3.7
  - imagesize=1.4.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - inflection=0.5.1
  - intel-openmp=2024.2.1
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - isort=5.13.2
  - jaraco.classes=3.2.1
  - jedi=0.19.1
  - jellyfish=1.0.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyterlab_pygments=0.2.2
  - keyring=24.3.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=17.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=2.0.4
  - mkl=2024.2.2
  - more-itertools=10.3.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - numpy=1.24.4
  - numpydoc=1.5.0
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.10.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pthreads-win32=2.9.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.4.0
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pylint=3.2.7
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyomo=6.2
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.0
  - python-slugify=5.0.2
  - python-tzdata=2024.2
  - python_abi=3.8
  - pytoolconfig=1.2.6
  - pytz=2024.1
  - pyuca=1.2
  - pywin32=305
  - pywin32-ctypes=0.2.2
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.3.1
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.32.3
  - rich=13.7.1
  - rope=1.12.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=6.0.1
  - spyder-kernels=3.0.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - superqt=0.6.7
  - sympy=1.13.2
  - tbb=2021.13.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tomli=2.0.1
  - tomlkit=0.13.2
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - yapf=0.40.2
  - yarl=1.11.0
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
